import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Cards from '@/components/cards'
import styles from '@/styles/Home.module.css'
import Footer from '@/components/Footer'
import style from '@/styles/Footer.module.css'
import cardslist from '../public/lista.json'
import { useEffect, useState } from 'react'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [carrito, setCarrito] = useState(0)

  useEffect(() => {
    alert("Elementos en el carrito: " + carrito)
  }, [carrito])

 
  return (
    <>
   
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Jhon mi Reat App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>    
          <Navbar /> 
          <section className= {styles.seccion}>
          <h4>Carrito: {carrito}</h4> 
        {
            cardslist.map(cards => 
            <Cards titulo={cards.title} descripcion={cards.description} imgUrl={cards.imgUrl} setCarrito={setCarrito} />
            )
        }
        </section>
        <footer className={style.pie} >
          <Footer />
        </footer>
        
      </main>
    </>
  )
}
