import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>Jhon mi Reat App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className={styles.navbar}>
          <Navbar />
        </header>
        <section className={styles.section}>secion1</section>  
        <section className={styles.section}>secion2</section>
        <section className={styles.section}>secion3</section>  

        <footer className={styles.footer}>
         
          <Footer />
        
        </footer> 
      </main>
    </>
  )
}
